
CREATE TABLE COFFEE(
	COF_NAME VARCHAR(32) NOT NULL PRIMARY KEY,
	SUP_ID INTEGER,
	PRICE NUMERIC(5, 2),
	SALES INTEGER,
	TOTAL NUMERIC(5, 2)
)

INSERT INTO COFFEE VALUES('Columbian', 101, 7.99, 0, 0);
insert into COFFEE VALUES('Espresso', 150, 9.99, 0, 0);
insert into coffee VALUES('Turkish', 49, 10.99, 0, 0);

SELECT * FROM COFFEE

DROP TABLE SPECIES

DROP TABLE animal

